# Keras Basics

A very simple (introductory) CV classfication application using Keras library

In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('./DATA/bank_note_data.txt', delimiter = ',')
print(data)

[[  3.6216    8.6661   -2.8073   -0.44699   0.     ]
 [  4.5459    8.1674   -2.4586   -1.4621    0.     ]
 [  3.866    -2.6383    1.9242    0.10645   0.     ]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771    1.     ]
 [ -3.5637   -8.3827   12.393    -1.2823    1.     ]
 [ -2.5419   -0.65804   2.6842    1.1952    1.     ]]


In [3]:
# Features
X = data[:, 0:-1]
print(X)

# Actual Values
y = data[:, -1]
print(y)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]
[0. 0. 0. ... 1. 1. 1.]


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler_obj = MinMaxScaler()

# We fit only to X_train so that we don't peek into what's inside test data yet.
scaler_obj.fit(X_train)

X_train = scaler_obj.transform(X_train)
X_test = scaler_obj.transform(X_test)

In [7]:
from keras.models import Sequential
from keras.layers import Dense

### Create the Neural Network, start with model = Sequential()

In [8]:
model = Sequential()

model.add(Dense(units = 4, input_dim = 4, activation = "relu"))
model.add(Dense(units = 8, activation = "relu"))
model.add(Dense(units = 8, activation = "relu"))
model.add(Dense(units = 1, activation = "sigmoid"))

In [9]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(X_train, y_train, epochs = 50, verbose = 2)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/50
 - 1s - loss: 0.6923 - accuracy: 0.5552
Epoch 2/50
 - 0s - loss: 0.6880 - accuracy: 0.5708
Epoch 3/50
 - 0s - loss: 0.6820 - accuracy: 0.6177
Epoch 4/50
 - 0s - loss: 0.6727 - accuracy: 0.6667
Epoch 5/50
 - 0s - loss: 0.6572 - accuracy: 0.6792
Epoch 6/50
 - 0s - loss: 0.6272 - accuracy: 0.6990
Epoch 7/50
 - 0s - loss: 0.5888 - accuracy: 0.7510
Epoch 8/50
 - 0s - loss: 0.5363 - accuracy: 0.7948
Epoch 9/50
 - 0s - loss: 0.4892 - accuracy: 0.8094
Epoch 10/50
 - 0s - loss: 0.4438 - accuracy: 0.8417
Epoch 11/50
 - 0s - loss: 0.3995 - accuracy: 0.8802
Epoch 12/50
 - 0s - loss: 0.3609 - accuracy: 0.8958
Epoch 13/50
 - 0s - loss: 0.3285 - accuracy: 0.9031
Epoch 14/50
 - 0s - loss: 0.2978 - accuracy: 0.9094
Epoch 15/50
 - 0s - loss: 0.2745 - accuracy: 0.9240
Epoch 16/50
 - 0s - loss: 0.2514 - accuracy: 0.9229
Epoch 17/50
 - 0s - loss: 0.2318 - accuracy: 0.9312
Epoch 18/50
 - 0s - loss: 0.21

In [10]:
predictions = model.predict_classes(X_test)

In [11]:
from sklearn.metrics import confusion_matrix, classification_report

confusion_matrix(y_test, predictions)

array([[226,   3],
       [  0, 183]], dtype=int64)

In [12]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99       229
         1.0       0.98      1.00      0.99       183

    accuracy                           0.99       412
   macro avg       0.99      0.99      0.99       412
weighted avg       0.99      0.99      0.99       412



In [13]:
model.save('bank_notes_validator.h5')

In [14]:
from keras.models import load_model

bank_notes_validator = load_model('bank_notes_validator.h5')
predictions = bank_notes_validator.predict_classes(X_test)
confusion_matrix(y_test, predictions)

array([[226,   3],
       [  0, 183]], dtype=int64)